name: Docker Migration

on:
  push:
    branches:
      - '*'

jobs:
  migration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install docker.io -y

    - name: Log into Docker
      run: |
        echo ${{ secrets.DOCKERHUB_USERNAME }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Run Docker container
      run: |
        docker run --rm \
          -e FLYWAY_BASELINE_ON_MIGRATE=true \
          -v ${{ github.workspace }}/sql:/flyway/sql \
          -v ${{ github.workspace }}/conf/homolog:/flyway/conf \
          flyway/flyway migrate \
          -url=jdbc:sqlserver://172.26.16.1:1433;databaseName=DBHomolog \
          -user=admin \
          -password=123456
